// Quy tắt comment: chỉ giải nghĩa logic của hàm, không comment thêm gì khác.

// Command genplugins sinh danh sách blank-import cho các plugin. Quét plugins/:
// mỗi package có gọi plugin.Register là một plugin. Chạy qua `go generate ./...`.
// Ranh giới hai tầng: thư mục quyết cái gì CÓ trong registry (file này), config
// quyết cái gì được DỰNG lúc chạy.
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	pluginsDir = "plugins"
	outFile    = "plugins_gen.go"
	importBase = "won/proxy/plugins"
)

func main() {
	names, err := scan(pluginsDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genplugins:", err)
		os.Exit(1)
	}
	if err := write(outFile, names); err != nil {
		fmt.Fprintln(os.Stderr, "genplugins:", err)
		os.Exit(1)
	}
	fmt.Printf("genplugins: %d plugin → %s [%s]\n", len(names), outFile, strings.Join(names, ", "))
}

// scan trả tên các package dưới plugins/ có gọi plugin.Register — dấu một
// plugin tự đăng ký. Thư mục không có dấu ấy bị bỏ qua: chưa phải plugin.
func scan(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		ok, err := registers(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, err
		}
		if ok {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	return names, nil
}

// registers báo package tại path có gọi plugin.Register trong file thường
// (bỏ _test.go). Đọc bằng AST để không nhận nhầm chuỗi nằm trong comment.
func registers(path string) (bool, error) {
	files, err := os.ReadDir(path)
	if err != nil {
		return false, err
	}
	fset := token.NewFileSet()
	for _, f := range files {
		name := f.Name()
		if f.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		full := filepath.Join(path, name)
		file, err := parser.ParseFile(fset, full, nil, 0)
		if err != nil {
			return false, fmt.Errorf("%s: %w", full, err)
		}
		if callsRegister(file) {
			return true, nil
		}
	}
	return false, nil
}

// callsRegister tìm một lời gọi dạng plugin.Register(...) ở bất kỳ đâu trong file.
func callsRegister(file *ast.File) bool {
	found := false
	ast.Inspect(file, func(n ast.Node) bool {
		if found {
			return false
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		if pkg, ok := sel.X.(*ast.Ident); ok && pkg.Name == "plugin" && sel.Sel.Name == "Register" {
			found = true
			return false
		}
		return true
	})
	return found
}

// write sinh plugins_gen.go — package main chỉ chứa blank-import. Đi qua
// format.Source để đầu ra luôn sạch gofmt.
func write(out string, names []string) error {
	var sb strings.Builder
	// Dòng luật comment cũng phải sinh ra ở đây: đóng dấu tay vào file sinh tự động
	// thì lần `go generate` kế tiếp xoá mất, và cây lại lệch một file.
	sb.WriteString("// Quy tắt comment: chỉ giải nghĩa logic của hàm, không comment thêm gì khác.\n\n")
	sb.WriteString("// Code generated by tools/genplugins; DO NOT EDIT.\n")
	sb.WriteString("// Run `go generate ./...` after adding/removing plugins in plugins/.\n\n")
	sb.WriteString("package main\n")
	if len(names) > 0 {
		sb.WriteString("\nimport (\n")
		for _, n := range names {
			fmt.Fprintf(&sb, "\t_ %q\n", importBase+"/"+n)
		}
		sb.WriteString(")\n")
	}
	src, err := format.Source([]byte(sb.String()))
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile(out, src, 0o644)
}
