// Quy tắt comment: chỉ giải nghĩa logic của hàm, không comment thêm gì khác.

// Code generated by tools/genplugins; DO NOT EDIT.
// Run `go generate ./...` after adding/removing plugins in plugins/.

package main

import (
	_ "won/proxy/plugins/identity"
	_ "won/proxy/plugins/loiterer"
	_ "won/proxy/plugins/memory"
	_ "won/proxy/plugins/outfitter"
	_ "won/proxy/plugins/wayfarer"
)
